- Pulled velocity engine initialization code to servlet startup in HarvesterProcessor. - Added better error handling to bash scripts. - Added skeleton getPast request to HarvestRESTController in HarvesterClient.
git-svn-id: http://svn.nla.gov.au/svn/public/nlaharvester/trunk@111 775b9859-8e63-0410-9d1e-8bd1c4a20c51

diff --git a/scripts/compileandcopytodeploymentfolder b/scripts/compileandcopytodeploymentfolder
--- a/scripts/compileandcopytodeploymentfolder
+++ b/scripts/compileandcopytodeploymentfolder
@@ -1,7 +1,13 @@
 #!/bin/bash
 cd ..
 echo NOTE! Tests are not being run, please run them seperately if you need to
+
 mvn -Dmaven.test.skip=true package
+if [ "$?" -ne 0 ]; then
+  echo "Build failed"
+  exit 1
+fi
+
 cd scripts
 echo -----------------COMPILING COMPLETE
 echo deleting current deployment folder
